//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Mongolia : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean BookMenu
        {
            get
            {
                return SteamVR_Actions.mongolia_BookMenu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Walking
        {
            get
            {
                return SteamVR_Actions.mongolia_Walking;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.mongolia_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.mongolia_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Map
        {
            get
            {
                return SteamVR_Actions.mongolia_Map;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnPageOrTeleportLeft
        {
            get
            {
                return SteamVR_Actions.mongolia_TurnPageOrTeleportLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnPageOrTeleportRight
        {
            get
            {
                return SteamVR_Actions.mongolia_TurnPageOrTeleportRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Continue
        {
            get
            {
                return SteamVR_Actions.mongolia_Continue;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cancel
        {
            get
            {
                return SteamVR_Actions.mongolia_Cancel;
            }
        }
        
        public virtual SteamVR_Action_Vibration Vibration
        {
            get
            {
                return SteamVR_Actions.mongolia_Vibration;
            }
        }
    }
}
